"""
vibehack/reporting/exporter.py — Markdown (and future PDF) audit report generator.

The report follows a structure common in professional pentest deliverables:
  1. Executive Summary
  2. Findings sorted by severity with CVSS-style badges
  3. Detailed per-finding breakdown (evidence, remediation)
  4. Appendix: full attack path / operational command log
"""
import json
from datetime import datetime
from pathlib import Path
from typing import List, Dict
from vibehack import __version__

try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False

from vibehack.llm.provider import Finding

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}

SEVERITY_BADGE = {
    "critical": "🔴 CRITICAL",
    "high":     "🟠 HIGH",
    "medium":   "🟡 MEDIUM",
    "low":      "🔵 LOW",
    "info":     "⚪ INFO",
}


def _sort_findings(findings: List[Finding]) -> List[Finding]:
    return sorted(findings, key=lambda f: SEVERITY_ORDER.get(f.severity.lower(), 9))


def _finding_row(f: Finding) -> str:
    badge = SEVERITY_BADGE.get(f.severity.lower(), f.severity.upper())
    return f"| {badge} | {f.title} | {f.description[:60]}{'...' if len(f.description) > 60 else ''} |"


def _extract_commands(history: List[Dict[str, str]]) -> List[dict]:
    """Pull proposed commands and their exit codes from the history."""
    commands = []
    for i, msg in enumerate(history):
        if msg["role"] != "assistant":
            continue
        try:
            data = json.loads(msg["content"])
        except (json.JSONDecodeError, TypeError):
            continue

        cmd = data.get("raw_command")
        if not cmd:
            continue

        # Try to grab the exit code from the next user message
        exit_code = "?"
        if i + 1 < len(history) and history[i + 1]["role"] == "user":
            next_content = history[i + 1]["content"]
            import re
            match = re.search(r"EXIT_CODE:\s*(\d+)", next_content)
            if match:
                exit_code = match.group(1)

        commands.append({
            "thought": data.get("thought", "")[:120],
            "command": cmd,
            "exit_code": exit_code,
            "is_destructive": data.get("is_destructive", False),
        })

    return commands


def generate_markdown_report(
    target: str,
    findings: List[Finding],
    history: List[Dict[str, str]],
) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    sorted_findings = _sort_findings(findings)
    commands = _extract_commands(history)

    # ── Severity counts ───────────────────────────────────────────────────
    counts = {s: 0 for s in SEVERITY_ORDER}
    for f in findings:
        counts[f.severity.lower()] = counts.get(f.severity.lower(), 0) + 1

    risk_line = " | ".join(f"**{k.capitalize()}**: {v}" for k, v in counts.items() if v > 0)
    overall_risk = "CRITICAL" if counts["critical"] else ("HIGH" if counts["high"] else ("MEDIUM" if counts["medium"] else "LOW"))

    report = f"""# 🛡️ Vibe_Hack Security Audit Report
# 
> **Automated report generated by Vibe_Hack v{__version__} (Autonomous Audit Engine)**

---

## 1. Executive Summary

| Field         | Value |
|---------------|-------|
| **Target**    | `{target}` |
| **Date**      | {now} |
| **Overall Risk** | **{overall_risk}** |
| **Findings**  | {len(findings)} total — {risk_line or "None"} |
| **Commands**  | {len(commands)} executed |

---

## 2. Findings Overview

| Severity | Title | Summary |
|----------|-------|---------|
"""

    if sorted_findings:
        for f in sorted_findings:
            report += _finding_row(f) + "\n"
    else:
        report += "| —  | No findings | No vulnerabilities confirmed in this session |\n"

    report += "\n---\n\n## 3. Findings (Detailed)\n"

    if not sorted_findings:
        report += "\n*No confirmed findings in this session.*\n"
    else:
        for idx, f in enumerate(sorted_findings, 1):
            badge = SEVERITY_BADGE.get(f.severity.lower(), f.severity.upper())
            report += f"""
### {idx}. {badge} — {f.title}

**Description**
{f.description}

**Evidence**
```
{f.evidence or "N/A"}
```

**Remediation**
{f.remediation or "*No remediation provided.*"}

---
"""

    report += "\n## 4. Attack Path (Operational Log)\n\n"
    report += "Commands proposed by the AI and executed by the operator:\n\n"

    if not commands:
        report += "*No commands were executed in this session.*\n"
    else:
        for i, entry in enumerate(commands, 1):
            destructive_tag = " ⚠️ *[DESTRUCTIVE]*" if entry["is_destructive"] else ""
            report += f"**Step {i}** — *{entry['thought']}*{destructive_tag}\n"
            report += f"```bash\n{entry['command']}\n```\n"
            report += f"Exit code: `{entry['exit_code']}`\n\n"

    report += (
        "\n---\n\n"
        "*This report was auto-generated. Manual review is recommended before sharing.*\n"
        "*Vibe_Hack is a gated security research tool. Use only on authorised targets.*\n"
    )

    return report


def generate_pdf_report(
    target: str,
    findings: List[Finding],
    commands: List[dict],
) -> bytes:
    if not FPDF_AVAILABLE:
        raise ImportError("fpdf2 is not installed. Run: vibehack install fpdf2")

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    sorted_findings = _sort_findings(findings)

    class PDF(FPDF):
        def header(self):
            # Safe ASCII header
            self.set_font("helvetica", "B", 14)
            self.cell(0, 10, f"Vibe_Hack v{__version__} Security Audit Report", border=False, align="C")
            self.ln(15)

        def footer(self):
            self.set_y(-15)
            self.set_font("helvetica", "I", 8)
            self.cell(0, 10, f"Page {self.page_no()} - Auto-generated by Vibe_Hack v{__version__}", align="C")

    pdf = PDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # ── 1. Executive Summary ──────────────────────────────────────────────
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(0, 10, "1. Executive Summary")
    pdf.ln(10)

    counts = {s: 0 for s in SEVERITY_ORDER}
    for f in findings:
        counts[f.severity.lower()] = counts.get(f.severity.lower(), 0) + 1
    overall_risk = "CRITICAL" if counts["critical"] else ("HIGH" if counts["high"] else ("MEDIUM" if counts["medium"] else ("LOW" if counts["low"] else "INFO")))

    pdf.set_font("helvetica", "", 11)
    pdf.cell(30, 8, "Target:", border=True)
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 8, f" {target}", border=True, ln=True)
    
    pdf.set_font("helvetica", "", 11)
    pdf.cell(30, 8, "Date:", border=True)
    pdf.cell(0, 8, f" {now}", border=True, ln=True)
    
    pdf.cell(30, 8, "Overall Risk:", border=True)
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 8, f" {overall_risk}", border=True, ln=True)

    pdf.set_font("helvetica", "", 11)
    pdf.cell(30, 8, "Findings:", border=True)
    risk_line = " | ".join(f"{k.capitalize()}: {v}" for k, v in counts.items() if v > 0)
    pdf.cell(0, 8, f" {len(findings)} total - {risk_line or 'None'}", border=True, ln=True)
    
    pdf.cell(30, 8, "Commands:", border=True)
    pdf.cell(0, 8, f" {len(commands)} executed", border=True, ln=True)
    pdf.ln(10)

    # ── 2. Findings Overview ──────────────────────────────────────────────
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(0, 10, "2. Findings Overview")
    pdf.ln(10)

    if not sorted_findings:
        pdf.set_font("helvetica", "I", 11)
        pdf.cell(0, 10, "No vulnerabilities confirmed in this session.")
        pdf.ln(10)
    else:
        pdf.set_font("helvetica", "B", 10)
        # Simplified table headers
        pdf.cell(30, 8, "Severity", border=True)
        pdf.cell(160, 8, "Title", border=True, ln=True)
        
        pdf.set_font("helvetica", "", 10)
        for f in sorted_findings:
            sev = f.severity.upper()
            title = f.title[:80] + ("..." if len(f.title) > 80 else "")
            
            # Basic text color matching severity
            if sev == "CRITICAL": pdf.set_text_color(200, 0, 0)
            elif sev == "HIGH": pdf.set_text_color(220, 100, 0)
            elif sev == "MEDIUM": pdf.set_text_color(220, 180, 0)
            elif sev == "LOW": pdf.set_text_color(0, 100, 255)
            else: pdf.set_text_color(100, 100, 100)
            
            pdf.cell(30, 8, f" {sev}", border=True)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(160, 8, f" {title}", border=True, ln=True)

    pdf.ln(10)

    # ── 3. Findings Detailed ──────────────────────────────────────────────
    pdf.add_page()
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(0, 10, "3. Findings (Detailed)")
    pdf.ln(10)

    for idx, f in enumerate(sorted_findings, 1):
        pdf.set_font("helvetica", "B", 12)
        pdf.cell(0, 10, f"{idx}. [{f.severity.upper()}] {f.title}")
        pdf.ln(8)
        
        pdf.set_font("helvetica", "B", 10)
        pdf.cell(0, 8, "Description")
        pdf.ln(6)
        pdf.set_font("helvetica", "", 10)
        # multi_cell gracefully wraps long text. encode/decode to protect against unknown unicode
        clean_desc = str(f.description).encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 6, clean_desc)
        pdf.ln(4)

        if f.evidence:
            pdf.set_font("helvetica", "B", 10)
            pdf.cell(0, 8, "Evidence")
            pdf.ln(6)
            pdf.set_font("courier", "", 9)
            clean_evid = str(f.evidence).encode('latin-1', 'replace').decode('latin-1')
            pdf.multi_cell(0, 5, clean_evid, border=True, fill=False)
            pdf.ln(4)

        pdf.set_font("helvetica", "B", 10)
        pdf.cell(0, 8, "Remediation")
        pdf.ln(6)
        pdf.set_font("helvetica", "", 10)
        clean_rem = str(f.remediation or "No remediation provided.").encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 6, clean_rem)
        pdf.ln(10)

    # ── 4. Attack Path ────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(0, 10, "4. Attack Path (Operational Log)")
    pdf.ln(10)

    if not commands:
        pdf.set_font("helvetica", "I", 11)
        pdf.cell(0, 10, "No commands executed in this session.")
    else:
        for i, entry in enumerate(commands, 1):
            warn = " [DESTRUCTIVE] " if entry["is_destructive"] else ""
            pdf.set_font("helvetica", "B", 10)
            clean_thought = str(entry['thought']).encode('latin-1', 'replace').decode('latin-1')
            pdf.multi_cell(0, 6, f"Step {i} — {clean_thought}{warn}")
            
            pdf.set_font("courier", "", 9)
            clean_cmd = str(entry['command']).encode('latin-1', 'replace').decode('latin-1')
            pdf.multi_cell(0, 5, clean_cmd, border=True, fill=False)
            
            pdf.set_font("helvetica", "I", 9)
            pdf.cell(0, 6, f"Exit code: {entry['exit_code']}")
            pdf.ln(8)

    pdf.ln(10)
    pdf.set_font("helvetica", "I", 8)
    pdf.cell(0, 10, "This report was auto-generated. Manual review is recommended before sharing.")

    return pdf.output(dest="S")


def export_report(
    target: str,
    findings: List[Finding],
    history: List[Dict[str, str]],
    output_dir: Path,
    fmt: str = "pdf"
) -> Path:
    """Write the report to disk (PDF or Markdown) and return the file path."""
    output_dir.mkdir(parents=True, exist_ok=True)
    safe_target = (
        target
        .replace("https://", "")
        .replace("http://", "")
        .replace("/", "_")
        .replace(":", "-")
    )
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    
    if fmt == "pdf":
        filename = f"report_{safe_target}_{timestamp}.pdf"
        file_path = output_dir / filename
        commands = _extract_commands(history)
        pdf_bytes = generate_pdf_report(target, findings, commands)
        file_path.write_bytes(pdf_bytes)
    else:
        filename = f"report_{safe_target}_{timestamp}.md"
        file_path = output_dir / filename
        content = generate_markdown_report(target, findings, history)
        file_path.write_text(content, encoding="utf-8")

    return file_path
